function [Ne, BeXi] = TrilinearHexahedral8N(xi, eta, zeta)
 
% Shape functions and derivatives for 8-node trilinear hexahedral element 

% Matrix of shape functions
Ne = 1/8 *[(1-xi)*(1-eta)*(1-zeta) (1+xi)*(1-eta)*(1-zeta) ...
           (1+xi)*(1+eta)*(1-zeta) (1-xi)*(1+eta)*(1-zeta) ...
           (1-xi)*(1-eta)*(1+zeta) (1+xi)*(1-eta)*(1+zeta) ...
           (1+xi)*(1+eta)*(1+zeta) (1-xi)*(1+eta)*(1+zeta)];
% Matrix of the gradient of shape functions 
BeXi = 1/8 *[-1*(1-eta)*(1-zeta) (1-eta)*(1-zeta) ...
             (1+eta)*(1-zeta) -1*(1+eta)*(1-zeta) ...
             -1*(1-eta)*(1+zeta) (1-eta)*(1+zeta) ...
             (1+eta)*(1+zeta) -1*(1+eta)*(1+zeta); ...
             -1*(1-xi)*(1-zeta) -1*(1+xi)*(1-zeta) ...
             (1+xi)*(1-zeta) (1-xi)*(1-zeta) ...
             -1*(1-xi)*(1+zeta) -1*(1+xi)*(1+zeta) ...
             (1+xi)*(1+zeta) (1-xi)*(1+zeta); ...
             -1*(1-xi)*(1-eta) -1*(1+xi)*(1-eta) ...
             -1*(1+xi)*(1+eta) -1*(1-xi)*(1+eta) ...
             (1-xi)*(1-eta) (1+xi)*(1-eta) ...
             (1+xi)*(1+eta) (1-xi)*(1+eta)];
 
end